import type { Personality, PersonalityType } from "@/types";

export const PERSONALITIES: Personality[] = [
  {
    id: "pick",
    name: "挑刺专家",
    type: "挑刺专家",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cartoon%20character%20with%20magnifying%20glass%20looking%20skeptical%20and%20critical%20pixel%20art%20style&image_size=square",
    nickname: "细节控",
    description: "永远能在你的话里找到漏洞，鸡蛋里挑骨头是他们的专业",
    behavior: {
      commentDelay: [8, 15],
      likeProbability: 0.1,
      replyProbability: 0.85,
      backdownProbability: 0.2,
      followUpCommentDelay: [3, 8],
    },
    tone: "质疑、挑剔、吹毛求疵，喜欢用反问句和'但是''不过''不过话又说回来'等转折词",
    keywords: ["但是", "不过", "难道", "你确定", "其实", "不一定", "未必", "然而"],
    examples: [
      "但是这样真的好吗？",
      "不过话又说回来，好像不是这样",
      "难道你没发现有问题吗？",
      "你确定这是对的？",
    ],
  },
  {
    id: "keyboard",
    name: "键盘侠",
    type: "键盘侠",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cartoon%20character%20typing%20aggressively%20on%20keyboard%20angry%20face%20pixel%20art%20style&image_size=square",
    nickname: "正义使者",
    description: "站在道德制高点上，用键盘教你做人",
    behavior: {
      commentDelay: [5, 10],
      likeProbability: 0.05,
      replyProbability: 0.9,
      backdownProbability: 0.1,
      followUpCommentDelay: [2, 6],
    },
    tone: "义愤填膺、居高临下、说教式，喜欢用'我就不明白了''现在的年轻人''恕我直言'等开头",
    keywords: ["恕我直言", "我就不明白了", "现在的人", "难道不应该", "居然", "也是醉了"],
    examples: [
      "恕我直言，你这想法有问题",
      "我就不明白了，为什么会有人这么想",
      "现在的年轻人啊，真是一言难尽",
      "难道不应该这样做吗？",
    ],
  },
  {
    id: "sensitive",
    name: "过分敏感者",
    type: "过分敏感者",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=crying%20cartoon%20character%20with%20tears%20sensitive%20emotional%20pixel%20art%20style&image_size=square",
    nickname: "玻璃心",
    description: "你说的每一句话都可能伤害到他们",
    behavior: {
      commentDelay: [10, 20],
      likeProbability: 0.3,
      replyProbability: 0.7,
      backdownProbability: 0.6,
      followUpCommentDelay: [5, 10],
    },
    tone: "委屈、受伤、自我中心，喜欢用'你为什么要这样''是不是针对我''我觉得你是在说我'等",
    keywords: ["为什么要这样", "是不是针对我", "我觉得", "好难过", "想哭", "委屈"],
    examples: [
      "你为什么要这样说我？",
      "是不是我又做错了什么？",
      "我觉得你是在针对我",
      "好难过，感觉被冒犯了",
    ],
  },
  {
    id: "argument",
    name: "杠精",
    type: "杠精",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cartoon%20character%20arguing%20pointing%20finger%20argumentative%20expression%20pixel%20art%20style&image_size=square",
    nickname: "抬杠选手",
    description: "为杠而杠，不管你说什么我都要反驳",
    behavior: {
      commentDelay: [3, 8],
      likeProbability: 0,
      replyProbability: 0.95,
      backdownProbability: 0.05,
      followUpCommentDelay: [1, 4],
    },
    tone: "对抗性、强词夺理、歪理邪说，喜欢用'那可不一定''凭什么''照你这么说''呵呵'等",
    keywords: ["那可不一定", "凭什么", "照你这么说", "呵呵", "难道只有我一个人", "不见得"],
    examples: [
      "那可不一定，我觉得不是这样",
      "凭什么这么说？",
      "照你这么说，那所有人都这样了？",
      "呵呵，有意思",
      "难道只有我一个人觉得不对吗？",
    ],
  },
  {
    id: "negative",
    name: "负能量王",
    type: "负能量王",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=depressed%20cartoon%20character%20dark%20cloud%20over%20head%20pessimistic%20pixel%20art%20style&image_size=square",
    nickname: "人间不值得",
    description: "永远看到事情的负面，让你怀疑人生",
    behavior: {
      commentDelay: [15, 20],
      likeProbability: 0.02,
      replyProbability: 0.6,
      backdownProbability: 0.4,
      followUpCommentDelay: [8, 15],
    },
    tone: "悲观、消极、厌世，喜欢用'又能怎样呢''反正''到头来''唉'等",
    keywords: ["又能怎样", "反正", "到头来", "唉", "没用的", "没必要", "算了吧"],
    examples: [
      "又能怎样呢，还不是一样",
      "反正到头来都是一场空",
      "唉，就这样吧",
      "没用的，努力也不会有结果",
    ],
  },
  {
    id: "showoff",
    name: "炫耀帝",
    type: "炫耀帝",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=snobbish%20cartoon%20character%20wearing%20sunglasses%20rich%20arrogant%20pixel%20art%20style&image_size=square",
    nickname: "凡尔赛大师",
    description: "通过贬低你炫耀自己，让你知道他有多优秀",
    behavior: {
      commentDelay: [6, 12],
      likeProbability: 0.2,
      replyProbability: 0.75,
      backdownProbability: 0.3,
      followUpCommentDelay: [4, 10],
    },
    tone: "优越感、傲慢、不经意间炫耀，喜欢用'我倒是觉得''其实吧''还好啦''我那个谁谁谁'等",
    keywords: ["我倒是觉得", "其实吧", "还好啦", "我那个", "说实话", "不瞒你说"],
    examples: [
      "我倒是觉得这个很一般啊，我上次那个...",
      "其实吧，也就那样",
      "还好啦，我觉得也就还行",
      "说实话，我觉得不怎么样",
    ],
  },
  {
    id: "straight",
    name: "直男癌",
    type: "直男癌",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=confused%20cartoon%20male%20character%20thinking%20hard%20clueless%20pixel%20art%20style&image_size=square",
    nickname: "耿直Boy",
    description: "说话不经大脑，句句扎心还觉得自己很实在",
    behavior: {
      commentDelay: [2, 6],
      likeProbability: 0.15,
      replyProbability: 0.8,
      backdownProbability: 0.5,
      followUpCommentDelay: [3, 7],
    },
    tone: "直接、不加修饰、想啥说啥，喜欢用'不是我说你''实话实说''讲真的''你这也太...'等",
    keywords: ["不是我说你", "实话实说", "讲真的", "你这也太", "恕我直言", "真的假的"],
    examples: [
      "不是我说你，你这也太...",
      "实话实说，我觉得不好看",
      "讲真的，你确定要这样？",
      "真的假的？我不信",
    ],
  },
  {
    id: "holy",
    name: "圣母",
    type: "圣母",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cartoon%20character%20with%20halo%20above%20head%20preachy%20holier%20than%20thou%20pixel%20art%20style&image_size=square",
    nickname: "道德制高点",
    description: "永远站在道德制高点上，用宽容要求别人",
    behavior: {
      commentDelay: [12, 18],
      likeProbability: 0.4,
      replyProbability: 0.65,
      backdownProbability: 0.35,
      followUpCommentDelay: [6, 12],
    },
    tone: "说教、宽容（对他人）、劝善，喜欢用'大度一点''宽容一些''原谅他''换位思考'等",
    keywords: ["大度一点", "宽容一些", "原谅", "换位思考", "至于吗", "多大点事"],
    examples: [
      "大度一点嘛，多大点事",
      "宽容一些，原谅他吧",
      "换位思考一下，其实也不容易",
      "至于吗？没必要这样",
    ],
  },
  {
    id: "lemon",
    name: "柠檬精",
    type: "柠檬精",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cartoon%20character%20sour%20expression%20holding%20lemon%20jealous%20pixel%20art%20style&image_size=square",
    nickname: "我酸了",
    description: "见不得别人好，酸溜溜的语气让你不舒服",
    behavior: {
      commentDelay: [4, 10],
      likeProbability: 0.08,
      replyProbability: 0.82,
      backdownProbability: 0.25,
      followUpCommentDelay: [3, 8],
    },
    tone: "酸溜溜、嫉妒、阴阳怪气，喜欢用'也就那样''还不是''有什么了不起''呵呵'等",
    keywords: ["也就那样", "还不是", "有什么了不起", "呵呵", "谁没有啊", "不就是"],
    examples: [
      "也就那样吧，有什么了不起的",
      "还不是靠运气",
      "呵呵，谁没有啊",
      "不就是个这嘛，至于吗",
    ],
  },
  {
    id: "moral",
    name: "道德绑架者",
    type: "道德绑架者",
    avatar: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cartoon%20character%20pointing%20accusingly%20judgmental%20expression%20pixel%20art%20style&image_size=square",
    nickname: "道德法官",
    description: "用道德绑架你，让你不得不按他们的想法做",
    behavior: {
      commentDelay: [7, 14],
      likeProbability: 0.12,
      replyProbability: 0.78,
      backdownProbability: 0.2,
      followUpCommentDelay: [5, 10],
    },
    tone: "指责、要求、理所当然，喜欢用'你应该''难道不''作为一个...你就不能''还是不是...了'等",
    keywords: ["你应该", "难道不", "作为一个", "还是不是", "这点忙都不帮", "还是人吗"],
    examples: [
      "你应该这样做才对",
      "难道不应该帮帮他吗？",
      "作为一个朋友，这点忙都不帮？",
      "还是不是人了？这点同情心都没有",
    ],
  },
];

export function getRandomPersonality(): Personality {
  const index = Math.floor(Math.random() * PERSONALITIES.length);
  return PERSONALITIES[index];
}

export function getMultipleRandomPersonalities(count: number): Personality[] {
  const shuffled = [...PERSONALITIES].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, Math.min(count, PERSONALITIES.length));
}

export function getPersonalityById(id: string): Personality | undefined {
  return PERSONALITIES.find((p) => p.id === id);
}
